export const columns = [
   {name: 'NAME PRODUCT', uid: 'name'},
   {name: 'PRICE', uid: 'price'},
   {name: 'STATUS', uid: 'status'},
   {name: 'CONDITON', uid: 'condition'},
  //  {name: 'DE', uid: 'actions'},
   {name: 'QUANTITY', uid: 'quantity'},
   {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
   {
     id: 1,
     name: "Sản phẩm A",
     count: 20,
     status: "Còn hàng",
     condition: "Mới",
     total: "$200",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 2,
     name: "Sản phẩm B",
     count: 15,
     status: "Hết hàng",
     condition: "Mới",
     total: "$150",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 3,
     name: "Sản phẩm C",
     count: 30,
     status: "Còn hàng",
     condition: "Cũ",
     total: "$300",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 4,
     name: "Sản phẩm D",
     count: 5,
     status: "Còn hàng",
     condition: "Mới",
     total: "$50",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 5,
     name: "Sản phẩm E",
     count: 10,
     status: "Còn hàng",
     condition: "Mới",
     total: "$100",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 6,
     name: "Sản phẩm F",
     count: 8,
     status: "Hết hàng",
     condition: "Cũ",
     total: "$80",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 7,
     name: "Sản phẩm G",
     count: 12,
     status: "Còn hàng",
     condition: "Mới",
     total: "$120",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 8,
     name: "Sản phẩm H",
     count: 0,
     status: "Hết hàng",
     condition: "Cũ",
     total: "$0",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 9,
     name: "Sản phẩm I",
     count: 25,
     status: "Còn hàng",
     condition: "Mới",
     total: "$250",
     actions: "Chỉnh sửa | Xóa",
   },
   {
     id: 10,
     name: "Sản phẩm J",
     count: 3,
     status: "Còn hàng",
     condition: "Cũ",
     total: "$30",
     actions: "Chỉnh sửa | Xóa",
   },
 ];
 
